SorceryのTwitterログインを実装
yuikotonoha/gender_quiz pull request #15
Opened 2019-12-05 09:01 UTC by yuikotonoha

## 概要
usersモデルを作成し、SorcerとTwitterを使用したログイン機能を実装。

■ログインに成功した場合（アプリ認証ページで「連携アプリを認証」をクリック」）
[![Image from Gyazo](https://i.gyazo.com/e7f9f7409f03556664746f049ec56a32.gif)](https://gyazo.com/e7f9f7409f03556664746f049ec56a32)

■ログインに失敗した場合（アプリ認証ページで「キャンセル」をクリック」）
[![Image from Gyazo](https://i.gyazo.com/100a1ec4ddcef57c0413cea108cad449.gif)](https://gyazo.com/100a1ec4ddcef57c0413cea108cad449)

## 確認方法
1. アプリ認証ページで「連携アプリを認証」をクリックした場合と、アプリ認証ページで「キャンセル」をクリックした場合で、上記のgifと同じ挙動が再現できるか確認をお願いいたします！
※検証にはTwitterアカウント必要です。
Twitterのapi_key と secret_key は`config/credentials.yml.enc`に暗号化して記載しているので、
レビューをして頂く際に、`config/master.key`をお送りいたします。

## チェックリスト
- [ ] rubocopをパスした

## コメント
■ログインに失敗した場合（アプリ認証ページで「キャンセル」をクリック」） の処理は下記の記事を参考にしました。
https://note.com/artefactnote/n/ne0089a217489

2019-12-05 09:30 UTC, yuji91 commented on app/controllers/oauths_controller.rb
> +      # redirect_to root_path, :notice => "#{provider.titleize}でログインしました!"
こちらのコメントは残しておく必要はありますか？？

2019-12-05 09:31 UTC, yuji91 commented on config/routes.rb
> +  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
RocketHashは使わない方が良いですね

2019-12-05 09:32 UTC, yuji91 commented on db/migrate/20191205034356_sorcery_core.rb
> +      t.timestamps null: false
登録するユーザーに性別のカラムは必要なくて大丈夫ですか？

2019-12-05 09:33 UTC, yuji91 commented on app/controllers/users_controller.rb
> +  skip_before_action :require_login, only: %i[new create]
コールバックとアクションの間は改行しておきましょうか

2019-12-05 09:33 UTC, yuji91 commented on app/views/oauths/oauth.html.slim
> +p Find me in app/views/oauths/oauth.html.slim
こちらのViewは不要かと思います！

2019-12-05 09:34 UTC, yuji91 commented on app/views/oauths/callback.html.slim
> +p Find me in app/views/oauths/callback.html.slim
こちらもなくて良いかと！

2019-12-05 09:34 UTC, yuji91 requested changes
コメントしました！

2019-12-05 10:00 UTC, yuikotonoha commented on db/migrate/20191205034356_sorcery_core.rb
> +      t.timestamps null: false
gender(性別）の値はusersテーブルではなく、resultsテーブルに持たせます！
※「ユーザー自身の性別が変わる」のではなく、「検証した結果(reslut)が女性に見えるか？男性に見えるか？」のため。
[![Image from Gyazo](https://i.gyazo.com/7b7661bebfb0681f764899d070d6833a.png)](https://gyazo.com/7b7661bebfb0681f764899d070d6833a)

ちなみにですが、顔認証のAPIでは下記のように値が返ってくるので、その値を元にresultのgenderカラムに性別のレコードを入れます！
■Amazon Rekognition（顔認証API）の値
```
 "Gender": {
                "Value": "Female",
                "Confidence": 95.77727508544922
            },
```
↑
gender: female
score: 95.77 
がresultsテーブルに格納される。

2019-12-05 10:04 UTC, yuikotonoha commented on app/controllers/oauths_controller.rb
> +      # redirect_to root_path, :notice => "#{provider.titleize}でログインしました!"
不要なコメントですね。
8289a09848382561618ddec21aa775204f2a5841
↑修正いたしました！

2019-12-05 10:04 UTC, yuikotonoha commented on config/routes.rb
> +  get 'oauth/:provider' => 'oauths#oauth', :as => :auth_at_provider
725bc4b12da686d1268e9861c3cc8171c2a8aed8
↑で修正いたしました！

2019-12-05 10:05 UTC, yuikotonoha commented on app/controllers/users_controller.rb
> +  skip_before_action :require_login, only: %i[new create]
49f5e31b2c4e0fb6d68123342bdf842a85b4ae07
↑で修正いたしました！

2019-12-05 10:06 UTC, yuikotonoha commented on app/views/oauths/oauth.html.slim
> +p Find me in app/views/oauths/oauth.html.slim
8428ccd78982d37d53cadfe84149ad1609a00968
↑で削除いたしました！

2019-12-05 10:06 UTC, yuikotonoha commented on app/views/oauths/callback.html.slim
> +p Find me in app/views/oauths/callback.html.slim
8428ccd78982d37d53cadfe84149ad1609a00968
↑で削除いたしました！

2019-12-05 10:32 UTC, DaichiSaito commented on app/views/layouts/application.html.slim
> +    = render 'shared/flash_message.html'
拡張子不要ですよね？

2019-12-05 10:35 UTC, yuji91 commented on db/migrate/20191205034356_sorcery_core.rb
> +      t.timestamps null: false
Userに性別を登録しても使用せず、使用しないカラムを登録するのも手間なので必要ないということでした。

2019-12-05 10:36 UTC, yuikotonoha commented on app/views/layouts/application.html.slim
> +    = render 'shared/flash_message.html'
d6645060635c37ad17a228d1ada57eb77e57e306
↑で修正いたしました！

2019-12-05 10:38 UTC, yuji91 approved these changes

2019-12-05 11:14 UTC, merged

2019-12-05 11:19 UTC, yuikotonoha commented
closed #5

2019-12-05 11:20 UTC, DaichiSaito commented on app/views/shared/_before_login_header.html.slim
> +        = link_to auth_at_provider_path(:provider => :twitter), class: "nav-item nav-link" do
ハッシュロケットはやめましょっか。

2019-12-07 07:14 UTC, yuikotonoha commented on app/views/shared/_before_login_header.html.slim
> +        = link_to auth_at_provider_path(:provider => :twitter), class: "nav-item nav-link" do
18001f6970db7700b299d299724869f6560d8d78 で修正