管理画面の作成（ログイン機能、ユーザー管理、検証結果管理、メッセージ文管理）
yuikotonoha/gender_quiz pull request #27
Opened 2019-12-13 04:24 UTC by yuikotonoha

## 概要
- 管理者権限を持たないユーザーや、ログインしてない状態で管理画面へアクセスできないように実装
[![Image from Gyazo](https://i.gyazo.com/f2452ae7e7b6caa8608b5148d0a22fb1.gif)](https://gyazo.com/f2452ae7e7b6caa8608b5148d0a22fb1)

- 管理画面の「ユーザー一覧」からユーザーの検索、ユーザーの削除ができるように実装
[![Image from Gyazo](https://i.gyazo.com/0cc70076e8deaa37c100aa24856baa19.gif)](https://gyazo.com/0cc70076e8deaa37c100aa24856baa19)

- 管理画面の「検証結果一覧」から検証結果の検索、検証結果の削除ができるように実装
[![Image from Gyazo](https://i.gyazo.com/64310947775cacad45470c9dc4c9a8b6.gif)](https://gyazo.com/64310947775cacad45470c9dc4c9a8b6)

- 管理画面の「メッセージ一覧」からメッセージ編集画面への遷移
- メッセージの編集ができるように実装
[![Image from Gyazo](https://i.gyazo.com/1007e820c0bf35a1222211c2b426ec2f.gif)](https://gyazo.com/1007e820c0bf35a1222211c2b426ec2f)

## テスト実行結果
[![Image from Gyazo](https://i.gyazo.com/7833d3123b7c023ad3f5ae3bc908bd6a.png)](https://gyazo.com/7833d3123b7c023ad3f5ae3bc908bd6a)

## 確認方法
1. ローカルにアプリをcloneした後、以下のコマンドをターミナルで実行
```
rails db:create
rails db:migrate
rails db:seed
rails s
```
2. 概要欄記載の機能確認をお願いいたします。
- 管理者権限を持たないユーザーや、ログインしてない状態で管理画面へアクセスできないように実装
- 管理画面の「ユーザー一覧」からユーザーの検索、ユーザーの削除ができるように実装
- 管理画面の「検証結果一覧」から検証結果の検索、検証結果の削除ができるように実装
- 管理画面の「メッセージ一覧」からメッセージ編集画面への遷移
- メッセージの編集ができるように実装

## チェックリスト
- [ ] rubocopをパスした

## コメント

2019-12-13 05:38 UTC, DaichiSaito reviewed
コメントしました！！

2019-12-13 05:38 UTC, DaichiSaito commented on app/controllers/admin/users_controller.rb
> +  layout 'admin_dashboards'
これは親クラスに書いたほうがスッキリしませんか？
他の子クラスも同様。

2019-12-13 05:38 UTC, DaichiSaito commented on app/controllers/admin/users_controller.rb
> +    @q = User.page(params[:page]).order(id: 'DESC').ransack(params[:q])
`id: :desc`のようなシンボルの方が推奨されてます。
他の同様箇所も直しておいてください。

2019-12-13 05:38 UTC, DaichiSaito commented on app/helpers/application_helper.rb
> +    return 'active' if controller_name == params[:controller]
`return`は省略できそう。

2019-12-13 05:38 UTC, DaichiSaito commented on app/helpers/application_helper.rb
> +  end
`full_title`とだいぶ被ってるので改善したいですね。
`full_title`に`admin`という引数を追加して、`base_title`を切り替えられるにようにするのはどうでしょうか？

2019-12-13 05:38 UTC, DaichiSaito commented on app/controllers/admin/user_sessions_controller.rb
> +  def admin_login; end
`new`でも良いと思ったのですがどうでしょうか？
デフォルトで生成される7つのアクション以外はあまり積極的に作らない方が良いですね。DHHもそう言ってます。

2019-12-13 05:38 UTC, DaichiSaito commented on app/controllers/admin/user_sessions_controller.rb
> +  def admin_logout
ここも同様。

2019-12-13 05:38 UTC, DaichiSaito commented on app/controllers/admin/users_controller.rb
> +    @user.destroy!
インスタンス変数にあえてする必要はないと思いました。

2019-12-13 05:38 UTC, DaichiSaito commented on app/views/admin/results/_result.html.slim
> +    = result.user.name
カリキュラムには出てきませんでしたが、こういう書き方を嫌う人も中にはいます。
「デメテルの法則」「delegate」がキーワードです。
直さなくても良いですが、頭に入れておいてください！

【参考】
https://qiita.com/lastcat_/items/f002eeb482319ed21163

2019-12-13 05:38 UTC, DaichiSaito commented on app/views/admin/results/index.html.slim
> +            th scope='col' 作成日時
並び替えられるようにしたくないですか？スコア順とか作成日時順とか。
実はransackにソートがめちゃめちゃ簡単にできる機能が備わってます。

後回しでも良いのでもしよかったら実装してみましょう。
https://github.com/activerecord-hackery/ransack#ransacks-sort_link-helper-creates-table-headers-that-are-sortable-links

2019-12-13 05:38 UTC, DaichiSaito commented on app/views/admin/results/show.html.slim
> +    | さんの検証結果
文字列と別行に書くなら文字列展開の形を取らなくても良いのかなと思いました。

2019-12-13 05:38 UTC, DaichiSaito commented on app/views/admin/shared/_footer.html.slim
> +  |  All rights reserved.
この辺も自分のアプリ用に変えちゃいましょうか。

2019-12-13 05:38 UTC, DaichiSaito commented on app/views/admin/shared/_sidemenu.html.slim
> +          = "#{current_user.name}"
ただ文字列をaタグの中に入れたいだけならブロックは使う必要ないですね。

2019-12-13 05:38 UTC, DaichiSaito commented on app/views/layouts/admin_user_sessions.html.slim
> +    meta content=('text/html; charset=UTF-8') http-equiv='Content-Type' /
viewportの指定がないとスマホ対応できない気がしますね！

2019-12-13 05:38 UTC, DaichiSaito commented on config/initializers/kaminari_config.rb
> +  config.default_per_page = 10
2,30あった方が見やすくないですかね？

2019-12-13 05:38 UTC, DaichiSaito commented on config/routes.rb
> +    get '/login', to: 'user_sessions#admin_login'
`user_sessions#new`で良いかな。
logoutに関しても同様。

2019-12-13 05:38 UTC, DaichiSaito commented on config/routes.rb
> +    get '/', to: 'dashboards#index'
`get '/'` よりも `root`の方がよりルート感が出て良いと思います。あと個人的な好みですがルートは一番上に書きたくなる。

2019-12-13 05:38 UTC, DaichiSaito commented on spec/factories/results.rb
> +    image { Rack::Test::UploadedFile.new("#{Rails.root}/spec/system/images/female1.jpg", 'image/png') }
おー、これですね昨日話してたやつ。

2019-12-13 05:38 UTC, DaichiSaito commented on spec/factories/results.rb
> +    gender { 'female' }
シンボルで指定できませんでしたっけ？

2019-12-13 05:38 UTC, DaichiSaito commented on spec/system/admin_screen_operation_spec.rb
> +    admin_user
`fill_in 'email', with: admin_user.email`
このタイミングで呼ばれるので、L9の`admin_uer`は不要ですね。

2019-12-13 06:11 UTC, yuikotonoha commented on app/controllers/admin/user_sessions_controller.rb
> +  def admin_login; end
確かに、、7つのアクションから外す意味がないですね・・・
修正します！

2019-12-13 06:42 UTC, yuikotonoha commented on app/views/admin/results/_result.html.slim
> +    = result.user.name
delegate 初めて知りました！
こういう書き方もあるんですね・・・
いい機会なので修正してみます！

2019-12-13 07:13 UTC, yuikotonoha commented on spec/factories/results.rb
> +    image { Rack::Test::UploadedFile.new("#{Rails.root}/spec/system/images/female1.jpg", 'image/png') }
これですね！
後から見直しできるように、教えてもらった参考URL貼っておきます！
https://stackoverflow.com/questions/55141549/attaching-activestorage-files-in-factorybot

2019-12-13 07:43 UTC, yuikotonoha commented on app/views/admin/results/index.html.slim
> +            th scope='col' 作成日時
ソート機能めっちゃいいですね！！！
「誰が高得点出したか？」とかすぐに特定できると便利なので導入します！！！！

2019-12-13 07:46 UTC, yuikotonoha commented on app/controllers/admin/users_controller.rb
> +  layout 'admin_dashboards'
5b08ceb305716ce3665846d227c3f2f35fed8c2b
↑で修正しました！

2019-12-13 07:47 UTC, yuikotonoha commented on app/controllers/admin/users_controller.rb
> +    @q = User.page(params[:page]).order(id: 'DESC').ransack(params[:q])
7105c380c6096a97c77379b692deed7c21f9866b
↑で修正しました！

2019-12-13 07:47 UTC, yuikotonoha commented on app/helpers/application_helper.rb
> +    return 'active' if controller_name == params[:controller]
6cd29eb2b2dff76831f0d170fb98634940523579
↑で修正しました！

2019-12-13 07:48 UTC, yuikotonoha commented on app/helpers/application_helper.rb
> +  end
c641c399a7b51067202d2590d02dbcb38425c24c
↑で修正しました！

2019-12-13 07:49 UTC, yuikotonoha commented on app/controllers/admin/user_sessions_controller.rb
> +  def admin_login; end
f38be1648aec40412a12bfc767de7bcc3273a93d
↑で修正しました！

2019-12-13 07:49 UTC, yuikotonoha commented on app/controllers/admin/user_sessions_controller.rb
> +  def admin_logout
f38be1648aec40412a12bfc767de7bcc3273a93d
↑で修正しました！

2019-12-13 07:49 UTC, yuikotonoha commented on app/controllers/admin/users_controller.rb
> +    @user.destroy!
aecbb58c5a8be79819d4287ea6215bcb5a88856d
↑で修正しました！

2019-12-13 07:49 UTC, yuikotonoha commented on app/views/admin/results/_result.html.slim
> +    = result.user.name
980c163224e045470d6258de4ca9179523645839
↑で修正しました！

2019-12-13 07:50 UTC, yuikotonoha commented on app/views/admin/results/index.html.slim
> +            th scope='col' 作成日時
d8cf025c0c65c5d2644bfb68ca7cb14a869faa54
↑で修正しました！

2019-12-13 07:51 UTC, yuikotonoha commented on app/views/admin/results/show.html.slim
> +    | さんの検証結果
756d375d22253978d8823e9feb65a23a7581a6fe
↑で修正しました！

2019-12-13 07:51 UTC, yuikotonoha commented on app/views/admin/shared/_footer.html.slim
> +  |  All rights reserved.
71136d66567dd0ecbe3cfd9dca74f08c7c39ed2d
↑で修正しました！

2019-12-13 07:52 UTC, yuikotonoha commented on app/views/admin/shared/_sidemenu.html.slim
> +          = "#{current_user.name}"
385c83d626fa8ecd0117ace58fb55c50988244f3
↑で修正しました！

2019-12-13 07:52 UTC, yuikotonoha commented on app/views/layouts/admin_user_sessions.html.slim
> +    meta content=('text/html; charset=UTF-8') http-equiv='Content-Type' /
9de492e1f4ac06d2738f08bff84a6686844c04ca
↑で修正しました！

2019-12-13 07:53 UTC, yuikotonoha commented on config/initializers/kaminari_config.rb
> +  config.default_per_page = 10
fea99f4d470e8fbf33a78bfd5ec73f12ec9f5567
↑で修正しました！

2019-12-13 07:53 UTC, yuikotonoha commented on config/routes.rb
> +    get '/login', to: 'user_sessions#admin_login'
f38be1648aec40412a12bfc767de7bcc3273a93d
↑で修正しました！

2019-12-13 07:54 UTC, yuikotonoha commented on config/routes.rb
> +    get '/', to: 'dashboards#index'
390a323bbd403e24d733a393bc0d61df20634b42
↑で修正しました！

2019-12-13 07:54 UTC, yuikotonoha commented on spec/factories/results.rb
> +    gender { 'female' }
831ad8ec39ab2328c0385641b4bbcfb4807bcc04
↑で修正しました！

2019-12-13 07:54 UTC, yuikotonoha commented on spec/system/admin_screen_operation_spec.rb
> +    admin_user
c74eaca76cdda433837085d12a064495ae68e994
↑で修正しました！

2019-12-14 06:55 UTC, yuikotonoha commented
> 条件分岐の中の返り値を返します。
初めて知りました・・・！

キーワード引数のアドバイスもありがとうございます！
57cf8cf8a4249b8ceca36d13a917b12b9ea6c75b
↑で修正しました！

2019-12-16 03:49 UTC, yuikotonoha commented
924404c99b4a583dffc24f62900030e923dfdad5
↑で修正しました！

2019-12-16 04:33 UTC, yuji91 commented on app/assets/stylesheets/admin.scss
> +@import "result";
シングルに統一しておきましょう！

2019-12-16 04:34 UTC, yuji91 commented on app/controllers/admin/results_controller.rb
> +  before_action :set_result, only: %i[show edit update destroy]
不要なアクションもonlyに定義されていますね。

2019-12-16 04:35 UTC, yuji91 commented on app/controllers/admin/user_sessions_controller.rb
> +  skip_before_action :admin_user?, only: %i[new create]
`admin_user?`という名前だと、判定の結果 trueかfalseを返すというイメージがあります。
そのメソッドを実行した結果、具体的に何をするメソッドかが分かるような命名にしましょう！

2019-12-16 04:38 UTC, yuji91 requested changes
レビューしました！

2019-12-16 04:57 UTC, yuikotonoha commented on app/assets/stylesheets/admin.scss
> +@import "result";
402ddbb61d89d36dda5cdb6eeebf250bbd4f7fff
↑で修正しました！

2019-12-16 04:57 UTC, yuikotonoha commented on app/controllers/admin/results_controller.rb
> +  before_action :set_result, only: %i[show edit update destroy]
6e6ebd30c209368b21309845f4f441ef9ab0683d
↑で修正しました！

2019-12-16 04:58 UTC, yuikotonoha commented on app/controllers/admin/user_sessions_controller.rb
> +  skip_before_action :admin_user?, only: %i[new create]
bb63852a8e48899c6f969df805a210f40b0b28fa
↑で修正しました！

2019-12-16 05:08 UTC, yuji91 commented on app/controllers/admin/base_controller.rb
>    end
`prohibit_access_except_admin_user`と動詞で始めた方が良いですね。

「管理者ユーザー以外のアクセスを禁止する」という内容が伝えられれば良いと思います。

2019-12-16 05:08 UTC, yuji91 requested changes
コメントしました。

2019-12-16 05:17 UTC, yuikotonoha commented on app/controllers/admin/base_controller.rb
>    end
参考メソッド、ありがとうございます！
4d781c64c244eec7fa5e527e10b433bf770b80c5
↑で修正しました！

2019-12-16 05:27 UTC, yuji91 commented on app/controllers/admin/user_sessions_controller.rb
> +  skip_before_action :prohibit_access_except_admin_user, only: %i[new create]
コールバックの後は改行した方が見やすいですね。

2019-12-16 05:30 UTC, yuji91 approved these changes
LGTM！

2019-12-16 05:33 UTC, merged